// app/src/routes/(app)/location/[slug]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import VibeCheck from '$lib/components/feedback/VibeCheck.svelte';

	let { data }: { data: PageData } = $props();

	let location = $derived(data.location);
	let initialVibeHistory = $derived(data.vibeHistory || []);
	let selectedActivityId = $state<string | null>(null);

	// Local state for optimistic updates
	let vibeHistory = $state<any[]>([]);

	$effect(() => {
		if (initialVibeHistory) {
			vibeHistory = [...initialVibeHistory];
		}
	});

	$effect(() => {
		if (location && location.activities.length > 0 && !selectedActivityId) {
			selectedActivityId = location.activities[0].id;
		}
	});

	function handleVibe(vibe: string) {
		// Optimistic update
		vibeHistory = [
			...vibeHistory,
			{
				id: Math.random().toString(),
				locationId: location.id,
				activityId: selectedActivityId,
				vibe: vibe,
				createdAt: new Date().toISOString()
			}
		];
	}

	let vibeCounts = $derived.by(() => {
		const counts: Record<string, number> = { sparkle: 0, fire: 0, chill: 0, nope: 0 };
		for (const v of vibeHistory) {
			if (counts[v.vibe] !== undefined) {
				counts[v.vibe]++;
			}
		}
		return counts;
	});
</script>

{#if location}
	<article class="relative flex min-h-screen flex-col bg-surface">
		<header class="relative h-[50vh] w-full overflow-hidden rounded-b-[3rem]">
			{#if location.image || (location.photos && location.photos[0])}
				<img
					src={location.image || location.photos![0]}
					alt={location.name}
					class="h-full w-full object-cover"
					style:view-transition-name="location-image-{location.slug}"
				/>
			{:else}
				<div class="bg-surface-container-high flex h-full w-full items-center justify-center">
					<span class="text-8xl">🏙️</span>
				</div>
			{/if}

			<div class="absolute inset-0 bg-gradient-to-t from-black/40 to-transparent"></div>

			<div class="absolute right-6 bottom-10 left-6">
				<h1 class="mb-2 font-display text-4xl font-black text-white sm:text-6xl">
					{location.name}
				</h1>
				<p class="text-lg font-medium text-white/90">{location.address || 'Address coming soon'}</p>
			</div>
		</header>

		<section
			class="bg-surface-container-low shadow-ambient relative z-10 -mt-12 flex-grow rounded-t-[3rem] px-6 pt-10"
		>
			<div class="mb-10 flex flex-wrap gap-2">
				{#each location.activities as activity (activity.id)}
					<button
						onclick={() => (selectedActivityId = activity.id)}
						class="rounded-full px-5 py-2 text-sm font-bold tracking-wide transition-all {selectedActivityId ===
						activity.id
							? `bg-peach text-white`
							: `bg-${activity.themeColor}/20 text-${activity.themeColor}-800`}"
					>
						{activity.icon}
						{activity.name}
					</button>
				{/each}
			</div>

			<div class="prose prose-neutral mb-12 max-w-none text-neutral-700">
				<p>{location.description || 'No description available yet.'}</p>
			</div>

			{#if selectedActivityId}
				<div class="bg-surface-container-lowest shadow-ambient mb-12 rounded-[2.5rem] p-8">
					<VibeCheck locationId={location.id} activityId={selectedActivityId} onVibe={handleVibe} />
				</div>
			{/if}

			<div class="bg-surface-container-lowest shadow-ambient mb-24 rounded-[2.5rem] p-8">
				<h3 class="mb-6 font-display text-2xl font-black text-neutral-800">✨ Vibe History</h3>
				{#if vibeHistory.length === 0}
					<p class="font-medium text-neutral-500 italic">
						No vibe checks yet. Be the first to drop one! 💖
					</p>
				{:else}
					<div class="grid grid-cols-2 gap-4 sm:grid-cols-4">
						{#if vibeCounts.sparkle > 0}
							<div
								class="flex flex-col items-center justify-center rounded-3xl bg-[#deffaf]/30 p-6 font-bold text-neutral-800 shadow-sm transition-transform hover:scale-105"
							>
								<span class="mb-2 text-4xl">✨</span>
								<span class="text-2xl">{vibeCounts.sparkle}</span>
							</div>
						{/if}
						{#if vibeCounts.fire > 0}
							<div
								class="flex flex-col items-center justify-center rounded-3xl bg-[#ff9e6d]/20 p-6 font-bold text-neutral-800 shadow-sm transition-transform hover:scale-105"
							>
								<span class="mb-2 text-4xl">🔥</span>
								<span class="text-2xl">{vibeCounts.fire}</span>
							</div>
						{/if}
						{#if vibeCounts.chill > 0}
							<div
								class="flex flex-col items-center justify-center rounded-3xl bg-blue-100/50 p-6 font-bold text-neutral-800 shadow-sm transition-transform hover:scale-105"
							>
								<span class="mb-2 text-4xl">🧊</span>
								<span class="text-2xl">{vibeCounts.chill}</span>
							</div>
						{/if}
						{#if vibeCounts.nope > 0}
							<div
								class="flex flex-col items-center justify-center rounded-3xl bg-neutral-100 p-6 font-bold text-neutral-800 shadow-sm transition-transform hover:scale-105"
							>
								<span class="mb-2 text-4xl">👎</span>
								<span class="text-2xl">{vibeCounts.nope}</span>
							</div>
						{/if}
					</div>
				{/if}
			</div>
		</section>
	</article>
{:else}
	<div class="flex h-screen items-center justify-center">
		<p class="animate-pulse font-bold text-peach">Loading the magic... ✨</p>
	</div>
{/if}

// wohin-app/app/location/[slug].tsx
import React, { useEffect, useState } from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity, Share } from 'react-native';
import { Image } from 'expo-image';
import { useLocalSearchParams, Stack } from 'expo-router';
import { VibeCheck } from '@/components/feedback/vibe-check';
import { PortableText } from '@/components/portable-text';
import { Skeleton } from '@/components/ui/skeleton';
import { Share2 } from 'lucide-react-native';
import { useAppTheme } from '@/hooks/use-app-theme';
import { useLocationDetail, useVibeHistory } from '@/hooks/use-queries';

export default function LocationDetailScreen() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const [selectedActivityId, setSelectedActivityId] = useState<string | null>(null);
  const theme = useAppTheme();

  // Load location detail and vibe history via queries
  const { data: location, isLoading: isLoadingLocation } = useLocationDetail(slug);
  const { data: vibeHistory = [] } = useVibeHistory(location?.id ?? "");

  useEffect(() => {
    if (location && location.activities.length > 0) {
      const hasActivity = location.activities.some(a => a.id === selectedActivityId);
      if (!hasActivity) {
        setSelectedActivityId(location.activities[0].id);
      }
    }
  }, [location, slug, selectedActivityId]);

  const vibeCounts = vibeHistory.reduce((acc: any, v) => {
    acc[v.vibe] = (acc[v.vibe] || 0) + 1;
    return acc;
  }, { sparkle: 0, fire: 0, chill: 0, nope: 0 });

  if (isLoadingLocation) {
    return (
      <View className="flex-1" style={{ backgroundColor: theme.background }}>
        <ScrollView showsVerticalScrollIndicator={false}>
          <Skeleton width="100%" height={400} borderRadius={0} />
          <View className="rounded-t-[40px] -mt-7 pt-8 px-6" style={{ backgroundColor: theme.background }}>
            <View className="flex-row gap-2 mb-8">
              <Skeleton width={100} height={40} borderRadius={20} />
              <Skeleton width={100} height={40} borderRadius={20} />
            </View>
            <Skeleton width="100%" height={20} style={{ marginBottom: 12 }} />
            <Skeleton width="90%" height={20} style={{ marginBottom: 12 }} />
            <Skeleton width="100%" height={150} borderRadius={32} style={{ marginTop: 20 }} />
          </View>
        </ScrollView>
      </View>
    );
  }

  if (!location) {
    return (
      <View className="flex-1 justify-center items-center" style={{ backgroundColor: theme.background }}>
        <Text style={{ color: theme.ink }}>Location not found</Text>
      </View>
    );
  }

  return (
    <View className="flex-1" style={{ backgroundColor: theme.background }}>
      <Stack.Screen options={{
        title: location.name,
        headerTransparent: true,
        headerTintColor: '#fff',
        headerRight: () => (
          <TouchableOpacity
            onPress={() => Share.share({
              title: location.name,
              message: `Check out ${location.name} on WOHIN!${location.address ? ` - ${location.address}` : ''}`,
              url: `wohinapp://location/${location.slug}`,
            })}
            className="p-2"
          >
            <Share2 size={22} color="#fff" />
          </TouchableOpacity>
        ),
      }} />

      <ScrollView showsVerticalScrollIndicator={false}>
        <View className="h-[400px] w-full relative">
          {location.image ? (
            <Image source={location.image} className="w-full h-full" contentFit="cover" />
          ) : (
            <View className="w-full h-full items-center justify-center" style={{ backgroundColor: theme.accent.peach + '20' }}>
              <Text className="text-[80px]">🏙️</Text>
            </View>
          )}
          <View className="absolute inset-0" style={{ backgroundColor: theme.overlay }} />
          <View className="absolute bottom-10 left-6 right-6">
            <Text className="text-4xl font-black text-white tracking-tighter">{location.name}</Text>
            <Text className="text-base font-semibold text-white/90 mt-1">{location.address || 'Address coming soon'}</Text>
          </View>
        </View>

        <View className="rounded-t-[40px] -mt-7 pt-8 px-6" style={{ backgroundColor: theme.background }}>
          <View className="mb-8">
            <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>
              {location.activities.map((activity) => (
                <TouchableOpacity
                  key={activity.id}
                  onPress={() => setSelectedActivityId(activity.id)}
                  className="px-5 py-2.5 rounded-[20px]"
                  style={StyleSheet.flatten([
                    selectedActivityId === activity.id 
                      ? { backgroundColor: theme.accent.peach } 
                      : { backgroundColor: theme.border }
                  ])}
                >
                  <Text style={{ color: theme.ink }}>{activity.icon} {activity.name}</Text>
                </TouchableOpacity>
              ))}
            </ScrollView>
          </View>

          <View className="mb-8">
            {Array.isArray((location as any).description) ? (
              <PortableText value={(location as any).description} />
            ) : (
              <Text className="text-base leading-6 opacity-80" style={{ color: theme.ink }}>No description available yet.</Text>
            )}
          </View>

          {selectedActivityId && (
            <View className="rounded-[32px] p-2 mb-8 shadow-sm" style={{ backgroundColor: theme.surface, shadowColor: theme.shadow }}>
              <VibeCheck
                locationId={location.id}
                activityId={selectedActivityId}
                onVibe={() => {}}
              />
            </View>
          )}

          <View className="rounded-[32px] p-6 mb-8 shadow-sm" style={{ backgroundColor: theme.surface, shadowColor: theme.shadow }}>
            <Text className="text-xl font-black mb-5" style={{ color: theme.ink }}>✨ Vibe History</Text>
            {vibeHistory.length === 0 ? (
              <Text className="text-sm italic" style={{ color: theme.muted }}>No vibe checks yet. Be the first to drop one! 💖</Text>
            ) : (
              <View className="flex-row flex-wrap gap-3">
                {Object.entries(vibeCounts).map(([key, count]) => (
                  count as number > 0 ? (
                    <View key={key} className="flex-1 min-w-[45%] rounded-3xl p-4 items-center justify-center" style={{ backgroundColor: theme.background }}>
                      <Text className="text-2xl mb-1">
                        {key === 'sparkle' ? '✨' : key === 'fire' ? '🔥' : key === 'chill' ? '🧊' : '👎'}
                      </Text>
                      <Text className="text-lg font-black" style={{ color: theme.ink }}>{count as number}</Text>
                    </View>
                  ) : null
                ))}
              </View>
            )}
          </View>
        </View>
        <View style={{ height: 100 }} />
      </ScrollView>
    </View>
  );
}
